### ISSUE TITLE
Improve documentation for public user-facing methods 

### ISSUE THREAD

**Issue by ColeJetton** [nasa/fmdtools#17]
Documentation at the top of some files needs some top-level descriptions of respective classes and functions along with potential reorganization to reflect the order in the code. Potentially reorganize some parts of the code to reflect Main vs Private methods.

**Analyze:**
- `graph.py` methods listed as functions instead of OOA class setup
- `plot.py`, the following functions need top-level description: `plot_line_and_err`, `plot_err_lines`, `multiplot_legent_title`, `make_consolidated_legend`, and `dyn_order`. The methods list could be reorganized to reflect the order in the code
- `result.py` all functions except `load` and `load_folder` could use descriptions.
- `tabulate.py` The following functions need top-level description: `label_faults`, `dicttab`, `maptab`, `phasefmea`, and `summfmea`. The methods list could be reorganized to reflect the order in the code

**Define:**
- `block.py` add a description for the following functions: `assoc_flows`, `inject_faults_internal`, and classes: `Simulable`, `GenericFxn`. The methods list could be reorganized to reflect the order in the code
- `common.py`, all functions need top-level descriptions.
- `model.py`, remove `ModelParam` top-level description. 
- `parameter.py` add description for `SimParam` class.
- `rand.py` add a description for the following functions `get_pdf_for_rand`, `get_scipy_pdf_helper`, and `get_pdf_for_dist`.

**Sim:**
- `approach.py` add description for `find_overlap_n`
- `propagate.py` Shared method parameters could be moved to the beginning of the description to reflect the order in the code, then paired with descriptions for all `kwargs` related functions. Potentially reorganize the order in the code (and description) to reflect the split of Main vs Private methods. Add descriptions for the following functions: `unpack _res_list`, `exec_nom_par`, `exec_nom_helper`, `nom_helper`, `scenlist_helper`, `exec_scen_par`, `exec_scen`, `check_hist_memory`, `check_mdl_memory`, `check_overwrite`, `phases_from_hist`, `init_histrange`,  `check_end_condition`, `get_result`, and `get_endclass_vars`. Remove descriptions of some private methods to reflect new setup (`propagate`, and `prop_time`).

**Comment by hulsed** [comment]
I've assigned you to the bug, so feel free to address on your remote and I'll merge in.

**Comment by hulsed** [comment]
@ColeJetton does that commit fix all the problems identified? If so I will close the issue

**Comment by ColeJetton** [comment]
Yes it should be good. I didn’t mess with any ordering in the code but each
function/class is now defined.
