### ISSUE TITLE
Local var 'b' not used

### ISSUE THREAD

**Issue by louwersj** [nasa/fmdtools#3]
The local variable 'b' is never used. I suppose we should remove this as it is useless and only clutters the codebase. 

[https://github.com/nasa/fmdtools/blob/6cbee6794e2bcb568a2861d12301056c74892e15/fmdtools/define/common.py#L101](https://github.com/nasa/fmdtools/blob/6cbee6794e2bcb568a2861d12301056c74892e15/fmdtools/define/common.py#L101)

Feel free to assign this to me and I will be happy to remove it.

**Comment by hulsed** [comment]
The purpose of this line is to test pickle.loads. b doesn't do anything in this instance, but it doesn't need to be removed.
