### ISSUE TITLE
unused import

### ISSUE THREAD

**Issue by louwersj** [nasa/fmdtools#4]
As far as I can see chain from itertools is not used anywhere in the codebase of common.py . Based upon that I argue it could be removed to clean the codebase and prevent unneeded memory use. 

https://github.com/nasa/fmdtools/blob/6cbee6794e2bcb568a2861d12301056c74892e15/fmdtools/define/common.py#L8

Feel free to assign this issue to me and I will remove it.

**Comment by hulsed** [comment]
Fixed in [4606520](https://github.com/nasa/fmdtools/commit/460652092d5b91e572d06778159d580d8f764693)

**Comment by louwersj** [comment]
Nice :-) Thanks
