### ISSUE TITLE
warnings import not used

### ISSUE THREAD

**Issue by louwersj** [nasa/fmdtools#5]
It looks like 'warnings' is imported however not used. This makes me believe it could be removed to clean the code and free memory. 

https://github.com/nasa/fmdtools/blob/6cbee6794e2bcb568a2861d12301056c74892e15/fmdtools/define/flow.py#L10

Feel free to assign this to me if neededd.

**Comment by hulsed** [comment]
Fixed in [4606520](https://github.com/nasa/fmdtools/commit/460652092d5b91e572d06778159d580d8f764693)
